name: Merge JS and CSS libraries
on: [push, pull_request]
env:
  PYTHON_SCRIPT: compile.py
  FINAL_FILENAME: simulacres_fiche_perso.html

jobs:
  merge_css_js:
    name: Compile Jinja template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the event commit
        uses: actions/checkout@v2
      - name: Load the JS and CSS libraries
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install  # yarn install
      - name: Compile Jinja template
        run: |
          mkdir -p target
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.FINAL_FILENAME }}
      - name: Upload the result file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FINAL_FILENAME }}
          path: target/${{ env.FINAL_FILENAME }}
