name: Produce character sheet
on: [push, pull_request]
env:
  PYTHON_SCRIPT: compile.py
  V7_BASE_FINAL_FILENAME: simulacres_v7_fiche_perso.html
  V7_LOCALISATION_FINAL_FILENAME: simulacres_v7_localisation_fiche_perso.html

jobs:
  produce_character_sheet:
    name: Produce character sheet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the event commit
        uses: actions/checkout@v2
      - name: Load the JS and CSS libraries
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install  # yarn install
      - name: Compile Jinja template
        run: |
          mkdir -p target
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V7_BASE_FINAL_FILENAME }}
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V7_LOCALISATION_FINAL_FILENAME }}
      - name: Upload the base v7 sheet
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V7_BASE_FINAL_FILENAME }}
          path: target/${{ env.V7_BASE_FINAL_FILENAME }}
      - name: Upload the v7 sheet with localisation
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V7_LOCALISATION_FINAL_FILENAME }}
          path: target/${{ env.V7_LOCALISATION_FINAL_FILENAME }}
