name: Produce character sheet
on: [ push, pull_request ]
env:
  PYTHON_SCRIPT: compile.py
  V7_BASE_FINAL_FILENAME: simulacres_v7_fiche_perso.html
  V7_LOCALISATION_FINAL_FILENAME: simulacres_v7_localisation_fiche_perso.html
  V7_LOCALISATION_DUAL_FINAL_FILENAME: simulacres_v7_localisation_deux_armes_fiche_perso.html
  V8_BASE_FINAL_FILENAME: simulacres_v8_fiche_perso.html
  V8_BASE_4x4_FINAL_FILENAME: simulacres_v8_fiche_perso_4x4.html
  V8_MINIMAL_FINAL_FILENAME: simulacres_v8_fiche_perso_minimale.html
  V8_MINIMAL_4x4_FINAL_FILENAME: simulacres_v8_fiche_perso_minimale_4x4.html
  V8_CAPTAIN_VOODOO_FINAL_FILENAME: simulacres_v8_fiche_perso_capitaine_vaudou.html
  V8_CAPTAIN_4x4_VOODOO_FINAL_FILENAME: simulacres_v8_fiche_perso_capitaine_vaudou_4x4.html
  V8_DISCOVERY_FINAL_FILENAME: simulacres_v8_fiche_perso_minimale_decouverte.html
  V8_DISCOVERY_4x4_FINAL_FILENAME: simulacres_v8_fiche_perso_minimale_decouverte_4x4.html

jobs:
  produce_character_sheet:
    name: Produce character sheet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the event commit
        uses: actions/checkout@v2
      - name: Load the JS and CSS libraries
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install  # yarn install
      - name: Compile Jinja template
        run: |
          mkdir -p target
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V7_BASE_FINAL_FILENAME }}
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V7_LOCALISATION_FINAL_FILENAME }} --localisation
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V7_LOCALISATION_DUAL_FINAL_FILENAME }} --localisation --dual-wielding
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_BASE_FINAL_FILENAME }} --version 8
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_MINIMAL_FINAL_FILENAME }} --version 8 --universe "Autre"
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_DISCOVERY_FINAL_FILENAME }} --version 8 --universe "Autre" --discovery --plugin plugins/plugin_generic_world.html
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_CAPTAIN_VOODOO_FINAL_FILENAME }} --version 8 --universe "Capitaine Vaudou"
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_BASE_4x4_FINAL_FILENAME }} --version 8 --matrix-4x4
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_MINIMAL_4x4_FINAL_FILENAME }} --version 8 --matrix-4x4 --universe "Autre"
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_DISCOVERY_4x4_FINAL_FILENAME }} --version 8 --matrix-4x4 --universe "Autre" --discovery --plugin plugins/plugin_generic_world.html
          python3 ${{ env.PYTHON_SCRIPT }} target/${{ env.V8_CAPTAIN_4x4_VOODOO_FINAL_FILENAME }} --version 8 --matrix-4x4 --universe "Capitaine Vaudou"

      - name: Upload the base v7 sheet
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V7_BASE_FINAL_FILENAME }}
          path: target/${{ env.V7_BASE_FINAL_FILENAME }}
      - name: Upload the v7 sheet with localisation
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V7_LOCALISATION_FINAL_FILENAME }}
          path: target/${{ env.V7_LOCALISATION_FINAL_FILENAME }}
      - name: Upload the v7 sheet with localisation and dual wielding
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V7_LOCALISATION_DUAL_FINAL_FILENAME }}
          path: target/${{ env.V7_LOCALISATION_DUAL_FINAL_FILENAME }}

      - name: Upload the base v8 sheet
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_BASE_FINAL_FILENAME }}
          path: target/${{ env.V8_BASE_FINAL_FILENAME }}
      - name: Upload the minimal v8 sheet
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_MINIMAL_FINAL_FILENAME }}
          path: target/${{ env.V8_MINIMAL_FINAL_FILENAME }}
      - name: Upload the Captain Voodoo sheet
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_CAPTAIN_VOODOO_FINAL_FILENAME }}
          path: target/${{ env.V8_CAPTAIN_VOODOO_FINAL_FILENAME }}

      - name: Upload the base v8 sheet with 4x4 matrix
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_BASE_4x4_FINAL_FILENAME }}
          path: target/${{ env.V8_BASE_4x4_FINAL_FILENAME }}
      - name: Upload the minimal v8 sheet with 4x4 matrix
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_MINIMAL_4x4_FINAL_FILENAME }}
          path: target/${{ env.V8_MINIMAL_4x4_FINAL_FILENAME }}
      - name: Upload the Captain Voodoo sheet with 4x4 matrix
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_CAPTAIN_4x4_VOODOO_FINAL_FILENAME }}
          path: target/${{ env.V8_CAPTAIN_4x4_VOODOO_FINAL_FILENAME }}
      - name: Upload the minimal v8 sheet in discovery mode
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_DISCOVERY_FINAL_FILENAME }}
          path: target/${{ env.V8_DISCOVERY_FINAL_FILENAME }}
      - name: Upload the minimal v8 sheet in discovery mode with 4x4 matrix
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.V8_DISCOVERY_4x4_FINAL_FILENAME }}
          path: target/${{ env.V8_DISCOVERY_4x4_FINAL_FILENAME }}
